// Контент раздела «Статьи и кейсы».
// Содержание ведётся в Telegram-канале + здесь дублируется лента.
window.SCHOOL = {
  hero: {
    eyebrow: 'JOURNAL · 2026',
    kicker: 'статьи · кейсы · разборы',
    title: 'Статьи\nи кейсы.',
    body: 'Разбираем механику D2C fashion-бренда — от орг-структуры до выхода на маркетплейсы. Кейсы выходят с реальными цифрами клиентов, статьи — с практическим чек-листом в конце.',
    body2: 'Новые материалы сначала выходят в Telegram-канале — подписывайтесь, чтобы не пропустить.',
    tg: { l: 't.me/anotherfashionagency', h: 'https://t.me/anotherfashionagency' },
    meta: [
      { k: 'кейсы',   v: 'с цифрами' },
      { k: 'статьи',  v: 'с чек-листом' },
      { k: 'формат',  v: 'lower than long-read' },
      { k: 'канал',   v: 'TG · сайт' },
    ],
  },

  // Категории-фильтры
  tabs: [
    { id: 'all',     l: 'Все' },
    { id: 'case',    l: 'Кейсы' },
    { id: 'article', l: 'Статьи' },
  ],

  // Лента: type · date · title · теги · href
  posts: [
    // ── Кейсы ──
    { type: 'case',    date: '2025·06·22', title: 'POST MERIDIEM на Farfetch', tags: ['маркетплейсы','глобал'],
      author: 'Andrey Kovalev', new: true,
      h: 'https://anotherfashion.agency/anotherfashionschool/post-meridiem-mirovie-rynki' },
    { type: 'case',    date: '2025·02·09', title: 'Разбор кейса: 2 орг-структуры. Ошибки и план развития + шаблон', tags: ['HR','команда'],
      author: 'Andrey Kovalev',
      h: 'https://anotherfashion.agency/anotherfashionschool/-org-structura-case' },
    { type: 'case',    date: '2024·06·01', title: 'Кейс: 12 STOREEZ — выход на международные рынки', tags: ['глобал'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-monochrome-nbsp-wtdwp' },
    { type: 'case',    date: '2024·06·01', title: 'Кейс: LAVARICE — выход на международные рынки', tags: ['глобал'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-monochrome-nbsp-wtdwp-6r3er' },
    { type: 'case',    date: '2024·05·26', title: 'Кейс: MONOCHROME — выход на международные рынки', tags: ['глобал'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-monochrome-nbsp' },

    // ── Статьи ──
    { type: 'article', date: '2025·02·02', title: 'Орг-структура в fashion-бизнесе: принципы, проблемы и пути развития', tags: ['HR','команда'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/org-chart-org-structura' },
    { type: 'article', date: '2024·09·07', title: 'Как построить эффективные отношения с маркетплейсом и вовремя от него уйти', tags: ['маркетплейсы','D2C'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-4' },
    { type: 'article', date: '2024·08·25', title: 'Как подготовиться к привлечению инвестиций для fashion-бренда', tags: ['финансы','инвестиции'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-fashion-2' },
    { type: 'article', date: '2024·08·11', title: 'D2C-бенчмарки для fashion-бизнеса', tags: ['D2C','цифры'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-d2c-fashion-benchmarks' },
    { type: 'article', date: '2024·07·21', title: 'Отчётность fashion-бизнеса', tags: ['финансы','отчёты'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/reports-for-fashion' },
    { type: 'article', date: '2024·06·30', title: 'Искусство использования скидок в fashion-индустрии', tags: ['обучение','маркетинг'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/9rle78fdorogrntt5bw5ngpbwzid7c' },
    { type: 'article', date: '2024·06·02', title: 'Критерии для выхода на глобальный рынок в 2024 году', tags: ['глобал'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-2024-nbsp' },
    { type: 'article', date: '2024·06·02', title: 'Контент и ассортимент для выхода в глобал', tags: ['глобал','контент'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-nbsp-' },
    { type: 'article', date: '2024·06·02', title: 'Поиск партнёра и источников финансирования для старта fashion-бизнеса', tags: ['финансы'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-fashion-' },
    { type: 'article', date: '2024·06·02', title: 'Как выйти на международный рынок: советы для российских брендов', tags: ['глобал'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-1' },
    { type: 'article', date: '2024·06·02', title: 'Вы придумали бренд, что дальше: ответы на главные вопросы', tags: ['обучение','старт'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-' },
    { type: 'article', date: '2024·06·02', title: 'Ключевые сотрудники: штат или аутсорс?', tags: ['HR','обучение'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-3' },
    { type: 'article', date: '2024·06·02', title: 'Производство: аутсорс или собственное?', tags: ['производство','обучение'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-2' },
    { type: 'article', date: '2024·06·02', title: 'Монопродукт или коллекция?', tags: ['продукт','обучение'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/nbsp-' },
    { type: 'article', date: '2024·06·23', title: 'Ценообразование fashion-бренда', tags: ['финансы','обучение'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/-fashion-1' },
    { type: 'article', date: '2024·05·27', title: 'Что должен уметь сайт для fashion-проекта', tags: ['web','D2C'],
      author: 'Svetlana Plotnikova',
      h: 'https://anotherfashion.agency/anotherfashionschool/Blog%20Post%20Title%20One-a3dy9' },
  ],

  cta: {
    eyebrow: '>>> подписаться',
    title: 'Свежие материалы\nв Telegram.',
    body: 'Новые кейсы и разборы выходят сначала в Telegram-канале. Подпишитесь, чтобы получать их первыми.',
    buttonLabel: 'Открыть Telegram',
    buttonHref: 'https://t.me/anotherfashionagency',
  },
};
